### ISSUE TITLE
Show correct planet image based on planet type

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#141]
**TODO: The correct image for the planet needs to be shown in the following locations:**
- [X] Galaxy page
- [x] Planet list in right sidebar
- [x] Planet abandon/rename popup (button on overview page)
- [x] Empire page (does not exist yet)
- [x] Note: PR #194 added more images which resulted in some duplicates. Check which version is the best to use and delete any duplicates.

---

A planet is always one of these types:

1. dry
2. desert
3. normal
4. jungle
5. water
6. ice
7. gas

See `PlanetService::getPlanetType()` for how the planet type is determined.

The [planet type] + [planet position in galaxy:system] makes up the unique "image". E.g. planet 1:1:15 with type "dry" would be "dry_15".

Images are stored in `/public/img/planets`. Note: not all images have been added to this folder yet. Any missing images will need to be retrieved and stored in the correct folder.

**Comment by Chewbaka69** [comment]
matching system of ogame to display planet by type:
![planets](https://www.zupimages.net/up/19/37/3v9n.png)
