### ISSUE TITLE
Resource production does not match shown values in tooltips

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#375]
## Problem summary
The resource production that the tooltip shows does not match the resource production that the "?" popup shows. I'm not sure yet if this has to do with server speed settings (economy) or if there is a bug somewhere else.

The screenshot for example shows the following differences all for metal mine level 1 with server settings economy speed/research speed/fleet speed all set to `1`.
- Tooltip shows per hour: `96`
- The metal mine "?" properties popup shows per hour: `220`
- The resource settings page shows per hour: `63` (30 base + 33 metal mine level 1)

## Todo
Investigate what causes these differences and adjust the logic so that the following places all show the correct resource production:

- [ ] Tooltip when hovering over the metal/crystal/deuterium/energy on top of the screen.
- [ ] The "?" properties popup of the respective buildings (metal mine, crystal mine, deuterium synthesizer, solar plant, fusion reactor)
- [ ] The resource settings page (URL `/resources/settings`) 
- [ ] Test with various server settings for economy speed to ensure all values always match.

### Screenshots

<img width="951" alt="Screenshot 2024-10-04 at 09 29 06" src="https://github.com/user-attachments/assets/de6a9444-f300-43b3-a9f3-b3f2263a610f">

<img width="719" alt="Screenshot 2024-10-04 at 09 33 54" src="https://github.com/user-attachments/assets/82c33722-379d-4c10-b340-386f546cdd3a">
