### ISSUE TITLE
Add background worker system for calculating and storing highscores

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#417]
The highscore system is already partially implemented. Points of players can be calculated, but currently this happens on-the-fly and highscores are not stored anywhere.

Because of this the highscore page at `/highscore` is currently limited to only show a maximum of `110` players as otherwise loading the page takes too long.

In order to improve the highscore performance we will need to offload this calculation to a background worker / cronjob process.

## Todo:

- [x] Add a background worker system that periodically, say every 5 minutes, recalculates highscores for all players and stores this information somewhere in the database.
- [x] Add this background worker to the Docker Compose setup so this background worker / process will automatically run when all Docker containers are started.
- [x] (Optionally) check if we can utilize cronjobs together with the background workers so OGameX Laravel installed without Docker can also work.
- [x] Update highscore page to retrieve highscores from the cached list in the database. Remove the `110` max player limit.
- [x] Update highscore menu link in the top menu bar which now reads like `Highscore (0)` and make the `0` show the actual player ranking in the highscore. E.g. if player is number 20 in the highscore list, the link should show `Highscore (20)`.

**Comment by lanedirt** [comment]
Implemented in #424.
